

// ERRORS
export const GET_ERRORS = 'GET_ERRORS';
export const EMPTY_ERRORS = 'EMPTY_ERRORS';
//Login /  Signup 
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const REGISTER_ACTION = 'REGISTER_ACTION';
export const SET_CUSTOMER_PASSWORD = 'SET_CUSTOMER_PASSWORD';
export const BEFORE_LOGIN = 'BEFORE_LOGIN';

// Products 
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const BEFORE_PRODUCTS = 'BEFORE_PRODUCTS';
// FAQS 
export const GET_FAQS = 'GET_FAQS';
export const BEFORE_FAQS = 'BEFORE_FAQS';
// SETITINGS
export const GET_SETTINGS = 'GET_SETTINGS';
export const BEFORE_SETIINGS = 'BEFORE_SETIINGS';
// CART
export const BEFORE_CART = 'BEFORE_CART';
export const CART_RETURNED = 'CART_RETURNED';
export const CART_ADDED = 'CART_ADDED';
export const CART_NOT_ADDED = 'CART_NOT_ADDED';
export const VALIDATE_COUPON = 'VALIDATE_COUPON';
export const INVALIDATE_COUPON = 'INVALIDATE_COUPON';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
// CHECKOUT
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const BEFORE_CHECKOUT = 'BEFORE_CHECKOUT';
export const ORDER_PLACED = 'ORDER_PLACED';
export const GET_ORDER = 'GET_ORDER';
export const BEFORE_CONTACT = 'BEFORE_CONTACT';
export const FORM_SUBMIT = 'FORM_SUBMIT';
// BANNER
export const GET_BANNERS = 'GET_BANNERS';
export const BEFORE_BANNER = 'BEFORE_BANNER';
// DASHBOARD
export const GET_USER = 'GET_USER';
export const GET_DATA = 'GET_DATA';
export const BEFORE_DASHBOARD = 'BEFORE_DASHBOARD';
export const GET_LISTING = 'GET_LISTING';
export const GET_DASHBOARD_ORDER = 'GET_DASHBOARD_ORDER';
export const GET_COUNTRY_DATA = 'GET_COUNTRY_DATA';
export const BEFORE_PROFILE = 'BEFORE_PROFILE';
export const UPSERT_USER = 'UPSERT_USER';
export const UPSERT_EXTRACT = 'UPSERT_EXTRACT';

//CMS
export const BEFORE_CMS = 'BEFORE_CMS';
export const GET_CMS = 'GET_CMS';
export const GET_FOOTER_PAGES = 'GET_FOOTER_PAGES';

// Content
export const GET_AUTH_HEADER_CONTENT = 'GET_AUTH_HEADER_CONTENT';
export const BEFORE_CONTENT = 'BEFORE_CONTENT';
export const GET_HEADER_CONTENT = 'GET_HEADER_CONTENT';



